"use client";
import { useEffect, useMemo, useState } from "react";
import { Dialog } from "@/components/shared/dialog"; import { FormField } from "@/components/shared/form-field"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Select } from "@/components/ui/select"; import { Textarea } from "@/components/ui/textarea"; import { toLocalDateKey } from "@/lib/date";
import type { IssueSolution, IssueSolutionDraft, IssueSeverity, IssueStatus, ParameterValue, TechnicalIssue, TechnicalIssueDraft, TestRecord, TestRecordDraft, TestResultStatus } from "@/types/testing"; import type { WorkspaceData } from "@/types/workspace";

function parseParameters(value: string): Record<string, ParameterValue> { const result: Record<string, ParameterValue> = {}; value.split("\n").forEach((line) => { const index = line.indexOf("="); if (index < 1) return; const key = line.slice(0, index).trim(); const raw = line.slice(index + 1).trim(); if (!key) return; if (raw === "true" || raw === "false") result[key] = raw === "true"; else if (raw && Number.isFinite(Number(raw))) result[key] = Number(raw); else result[key] = raw; }); return result; }
function stringifyParameters(value: Record<string, ParameterValue>) { return Object.entries(value).map(([key, item]) => `${key}=${String(item)}`).join("\n"); }

export function TestRecordDialog({ open, record, data, initialProjectId, onClose, onSubmit }: { open: boolean; record: TestRecord | null; data: WorkspaceData; initialProjectId?: string; onClose: () => void; onSubmit: (draft: TestRecordDraft, current: TestRecord | null) => void }) {
  const blank = useMemo(() => ({ projectId: initialProjectId ?? data.projects[0]?.id ?? "", moduleId: "", taskId: "", workLogId: "", title: "", testDate: toLocalDateKey(), environment: "", objective: "", procedure: "", inputParameters: "", measurements: "", expectedResult: "", actualResult: "", conclusion: "", resultStatus: "待复测" as TestResultStatus }), [data.projects, initialProjectId]); const [form, setForm] = useState(blank); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; setForm(record ? { projectId: record.projectId, moduleId: record.moduleId ?? "", taskId: record.taskId ?? "", workLogId: record.workLogId ?? "", title: record.title, testDate: record.testDate, environment: record.environment, objective: record.objective, procedure: record.procedure, inputParameters: stringifyParameters(record.inputParameters), measurements: stringifyParameters(record.measurements), expectedResult: record.expectedResult, actualResult: record.actualResult, conclusion: record.conclusion, resultStatus: record.resultStatus } : blank); setError(""); }, [blank, open, record]);
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.projectId || !form.title.trim()) { setError("请选择项目并填写测试标题。"); return; } onSubmit({ ...form, moduleId: form.moduleId || undefined, taskId: form.taskId || undefined, workLogId: form.workLogId || undefined, inputParameters: parseParameters(form.inputParameters), measurements: parseParameters(form.measurements), attachmentNames: [] }, record); onClose(); };
  const modules = data.projectModules.filter((item) => item.projectId === form.projectId); return <Dialog open={open} title={record ? "编辑测试记录" : "新增测试记录"} onClose={onClose} size="lg" footer={<><Button variant="outline" onClick={onClose}>取消</Button><Button type="submit" form="test-form">保存测试</Button></>}><form id="test-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><FormField label="项目" htmlFor="test-project" error={error}><Select id="test-project" value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value, moduleId: "" })}>{data.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField label="模块" htmlFor="test-module"><Select id="test-module" value={form.moduleId} onChange={(e) => setForm({ ...form, moduleId: e.target.value })}><option value="">未关联</option>{modules.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField label="标题" htmlFor="test-title"><Input id="test-title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></FormField><FormField label="测试日期" htmlFor="test-date"><Input id="test-date" type="date" value={form.testDate} onChange={(e) => setForm({ ...form, testDate: e.target.value })} /></FormField><FormField label="环境" htmlFor="test-env"><Input id="test-env" value={form.environment} onChange={(e) => setForm({ ...form, environment: e.target.value })} /></FormField><FormField label="结果状态" htmlFor="test-status"><Select id="test-status" value={form.resultStatus} onChange={(e) => setForm({ ...form, resultStatus: e.target.value as TestResultStatus })}>{(["通过", "部分通过", "失败", "待复测"] as TestResultStatus[]).map((item) => <option key={item}>{item}</option>)}</Select></FormField>{(["objective", "procedure", "expectedResult", "actualResult", "conclusion"] as const).map((key) => <div key={key} className={key === "procedure" ? "sm:col-span-2" : ""}><FormField label={{ objective: "测试目标", procedure: "测试步骤", expectedResult: "预期结果", actualResult: "实际结果", conclusion: "结论" }[key]} htmlFor={`test-${key}`}><Textarea id={`test-${key}`} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></FormField></div>)}<FormField label="输入参数" htmlFor="test-input" hint="每行 key=value"><Textarea id="test-input" value={form.inputParameters} onChange={(e) => setForm({ ...form, inputParameters: e.target.value })} /></FormField><FormField label="测量数据" htmlFor="test-measure" hint="每行 key=value"><Textarea id="test-measure" value={form.measurements} onChange={(e) => setForm({ ...form, measurements: e.target.value })} /></FormField></form></Dialog>;
}

export function IssueDialog({ open, issue, data, initialProjectId, onClose, onSubmit }: { open: boolean; issue: TechnicalIssue | null; data: WorkspaceData; initialProjectId?: string; onClose: () => void; onSubmit: (draft: TechnicalIssueDraft, current: TechnicalIssue | null) => void }) {
  const blank = useMemo(() => ({ projectId: initialProjectId ?? data.projects[0]?.id ?? "", moduleId: "", title: "", phenomenon: "", errorMessage: "", severity: "S3" as IssueSeverity, status: "待定位" as IssueStatus, reproductionSteps: "", probableCause: "", rootCause: "" }), [data.projects, initialProjectId]); const [form, setForm] = useState(blank); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; setForm(issue ? { projectId: issue.projectId, moduleId: issue.moduleId ?? "", title: issue.title, phenomenon: issue.phenomenon, errorMessage: issue.errorMessage, severity: issue.severity, status: issue.status, reproductionSteps: issue.reproductionSteps, probableCause: issue.probableCause, rootCause: issue.rootCause } : blank); setError(""); }, [blank, issue, open]);
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.projectId || !form.title.trim() || !form.phenomenon.trim()) { setError("请选择项目，并填写标题和问题现象。"); return; } const solved = form.status === "已解决"; onSubmit({ ...form, moduleId: form.moduleId || undefined, taskId: issue?.taskId, testRecordId: issue?.testRecordId, discoveredAt: issue?.discoveredAt ?? new Date().toISOString(), resolvedAt: solved ? issue?.resolvedAt ?? new Date().toISOString() : undefined }, issue); onClose(); };
  return <Dialog open={open} title={issue ? "编辑技术问题" : "新增技术问题"} onClose={onClose} size="lg" footer={<><Button variant="outline" onClick={onClose}>取消</Button><Button type="submit" form="issue-form">保存问题</Button></>}><form id="issue-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><FormField label="项目" htmlFor="issue-project" error={error}><Select id="issue-project" value={form.projectId} onChange={(e) => setForm({ ...form, projectId: e.target.value, moduleId: "" })}>{data.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><FormField label="模块" htmlFor="issue-module"><Select id="issue-module" value={form.moduleId} onChange={(e) => setForm({ ...form, moduleId: e.target.value })}><option value="">未关联</option>{data.projectModules.filter((item) => item.projectId === form.projectId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></FormField><div className="sm:col-span-2"><FormField label="标题" htmlFor="issue-title"><Input id="issue-title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></FormField></div><FormField label="严重程度" htmlFor="issue-severity"><Select id="issue-severity" value={form.severity} onChange={(e) => setForm({ ...form, severity: e.target.value as IssueSeverity })}>{(["S1", "S2", "S3"] as IssueSeverity[]).map((item) => <option key={item}>{item}</option>)}</Select></FormField><FormField label="状态" htmlFor="issue-status"><Select id="issue-status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as IssueStatus })}>{(["待定位", "调查中", "修复中", "待验证", "已解决", "不处理"] as IssueStatus[]).map((item) => <option key={item}>{item}</option>)}</Select></FormField>{(["phenomenon", "errorMessage", "reproductionSteps", "probableCause", "rootCause"] as const).map((key) => <div key={key} className="sm:col-span-2"><FormField label={{ phenomenon: "问题现象", errorMessage: "错误信息", reproductionSteps: "复现步骤", probableCause: "可能原因", rootCause: "根因（解决时填写）" }[key]} htmlFor={`issue-${key}`}><Textarea id={`issue-${key}`} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></FormField></div>)}</form></Dialog>;
}

export function SolutionDialog({ open, issue, solution, onClose, onSubmit }: { open: boolean; issue: TechnicalIssue | null; solution: IssueSolution | null; onClose: () => void; onSubmit: (draft: IssueSolutionDraft, current: IssueSolution | null) => void }) { const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [result, setResult] = useState(""); const [effective, setEffective] = useState(false); useEffect(() => { if (open) { setTitle(solution?.title ?? ""); setContent(solution?.content ?? ""); setResult(solution?.result ?? ""); setEffective(solution?.isEffective ?? false); } }, [open, solution]); return <Dialog open={open} title={`添加尝试方案${issue ? ` · ${issue.title}` : ""}`} onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>取消</Button><Button onClick={() => { if (!issue || !title.trim()) return; onSubmit({ issueId: issue.id, title, content, result, isEffective: effective, parametersBefore: solution?.parametersBefore ?? {}, parametersAfter: solution?.parametersAfter ?? {} }, solution); onClose(); }}>保存方案</Button></>}><div className="space-y-4"><FormField label="方案标题" htmlFor="solution-title"><Input id="solution-title" value={title} onChange={(e) => setTitle(e.target.value)} /></FormField><FormField label="方案内容" htmlFor="solution-content"><Textarea id="solution-content" value={content} onChange={(e) => setContent(e.target.value)} /></FormField><FormField label="验证结果" htmlFor="solution-result"><Textarea id="solution-result" value={result} onChange={(e) => setResult(e.target.value)} /></FormField><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={effective} onChange={(e) => setEffective(e.target.checked)} />标记为有效方案</label></div></Dialog>; }
