-- Allow native daily records alongside immutable migration provenance.

ALTER TABLE "Project" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "Attachment" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Attachment" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Attachment" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ProjectModule" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "ProjectModule" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ProjectModule" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ProjectMilestone" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "ProjectMilestone" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ProjectMilestone" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Task" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Task" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Task" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "EngineeringLog" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "EngineeringLog" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "EngineeringLog" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Experiment" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Experiment" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Experiment" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Knowledge" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Knowledge" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Knowledge" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Skill" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Skill" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Skill" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "SkillEvidence" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "SkillEvidence" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "SkillEvidence" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Timeline" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Timeline" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Timeline" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Semester" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Semester" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Semester" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Course" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Course" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Course" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Chapter" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Chapter" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Chapter" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ClassSession" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "ClassSession" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ClassSession" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Assignment" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Assignment" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Assignment" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Exam" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "Exam" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Exam" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "StudyPlan" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "StudyPlan" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "StudyPlan" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "StudySession" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "StudySession" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "StudySession" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReadingItem" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "ReadingItem" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ReadingItem" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "TechnicalIssue" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "TechnicalIssue" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "TechnicalIssue" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "IssueSolution" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "IssueSolution" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "IssueSolution" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReportRecord" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "ReportRecord" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ReportRecord" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ResumeMaterial" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "ResumeMaterial" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ResumeMaterial" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "CalendarEvent" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "CalendarEvent" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "CalendarEvent" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "FinanceTransaction" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "FinanceTransaction" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "FinanceTransaction" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ContentState" ALTER COLUMN "sourceHash" DROP NOT NULL, ALTER COLUMN "migrationBatchId" DROP NOT NULL, ALTER COLUMN "relationRefs" DROP NOT NULL;
ALTER TABLE "ContentState" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ContentState" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
