"use client";
import { useMemo, useState } from "react";
import { BookPlus, Bug, Edit3, List, Plus, Rows3, Trash2 } from "lucide-react";
import { WorkLogDialog } from "@/components/engineering/work-log-dialog";
import { ActionToast, type ToastNotice } from "@/components/layout/action-toast";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { EmptyState } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { useWorkspaceData } from "@/hooks/use-workspace-data";
import { formatChineseDate } from "@/lib/date";
import { cn } from "@/lib/utils";
import { createTechnicalIssue, createWorkLog, knowledgeFromWorkLog } from "@/services/engineering-service";
import type { WorkLog, WorkLogDraft, WorkLogResultStatus } from "@/types/engineering-log";
export function WorkLogCenter({ initialProjectId, initialTaskId, openCreate = false }: { initialProjectId?: string; initialTaskId?: string; openCreate?: boolean }) {
  const { data, dispatch } = useWorkspaceData(); const [query, setQuery] = useState(""); const [projectId, setProjectId] = useState(initialProjectId ?? ""); const [moduleId, setModuleId] = useState(""); const [result, setResult] = useState<WorkLogResultStatus | "全部">("全部"); const [date, setDate] = useState(""); const [tag, setTag] = useState(""); const [view, setView] = useState<"timeline" | "list">("timeline"); const [editing, setEditing] = useState<WorkLog | null>(null); const [formOpen, setFormOpen] = useState(openCreate); const [deleting, setDeleting] = useState<WorkLog | null>(null); const [notice, setNotice] = useState<ToastNotice | null>(null);
  const logs = useMemo(() => data.workLogs.filter((item) => (!query || `${item.title} ${item.workContent} ${item.result}`.toLowerCase().includes(query.toLowerCase())) && (!projectId || item.projectId === projectId) && (!moduleId || item.moduleId === moduleId) && (result === "全部" || item.resultStatus === result) && (!date || item.date === date) && (!tag || item.tags.some((value) => value.includes(tag)))).sort((a, b) => b.date.localeCompare(a.date)), [data.workLogs, date, moduleId, projectId, query, result, tag]);
  const save = async (draft: WorkLogDraft, current: WorkLog | null) => { await dispatch(current ? { type: "work-log/updated", workLog: { ...current, ...draft, updatedAt: new Date().toISOString() } } : { type: "work-log/added", workLog: createWorkLog(draft) }); setNotice({ id: Date.now(), title: "工程日志已保存", description: current ? "日志内容已更新。" : "关联任务的实际耗时已同步累计。" }); };
  return <div className="space-y-5"><PageHeader eyebrow="ENGINEERING LOG" title="工程日志" description="记录做了什么、得到什么结果、遇到什么问题，以及下一步计划。" actions={<Button onClick={() => { setEditing(null); setFormOpen(true); }}><Plus />新增日志</Button>} /><section className="grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-2 xl:grid-cols-7"><Input aria-label="搜索工程日志" placeholder="搜索标题、内容或结果" value={query} onChange={(e) => setQuery(e.target.value)} /><Select aria-label="日志项目" value={projectId} onChange={(e) => { setProjectId(e.target.value); setModuleId(""); }}><option value="">全部项目</option>{data.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="日志模块" value={moduleId} onChange={(e) => setModuleId(e.target.value)}><option value="">全部模块</option>{data.projectModules.filter((item) => !projectId || item.projectId === projectId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="日志结果" value={result} onChange={(e) => setResult(e.target.value as WorkLogResultStatus | "全部")}><option>全部</option>{(["完成", "部分完成", "受阻"] as WorkLogResultStatus[]).map((item) => <option key={item}>{item}</option>)}</Select><Input aria-label="日志日期" type="date" value={date} onChange={(e) => setDate(e.target.value)} /><Input aria-label="日志标签" placeholder="标签" value={tag} onChange={(e) => setTag(e.target.value)} /><div className="flex rounded border p-1"><button aria-label="时间线视图" onClick={() => setView("timeline")} className={cn("grid h-8 w-8 place-items-center", view === "timeline" && "bg-blue-50 text-blue-700")}><Rows3 className="h-4 w-4" /></button><button aria-label="紧凑列表视图" onClick={() => setView("list")} className={cn("grid h-8 w-8 place-items-center", view === "list" && "bg-blue-50 text-blue-700")}><List className="h-4 w-4" /></button></div></section>
    {logs.length ? <section className="space-y-3">{logs.map((log) => { const project = data.projects.find((item) => item.id === log.projectId); const projectModule = data.projectModules.find((item) => item.id === log.moduleId); return <article key={log.id} className={cn("rounded-lg border bg-white p-5 shadow-sm", view === "timeline" && "border-l-4 border-l-blue-500")}><div className="flex flex-col justify-between gap-4 lg:flex-row"><div className="min-w-0"><div className="flex flex-wrap gap-2 text-[10px]"><span className="rounded bg-blue-50 px-2 py-1 text-blue-700">{project?.name ?? "未知项目"}</span>{projectModule && <span className="rounded bg-slate-100 px-2 py-1">{projectModule.name}</span>}<span>{formatChineseDate(log.date)}</span><span>{log.resultStatus}</span><span>{log.durationMinutes} 分钟</span></div><h2 className="mt-3 text-base font-semibold">{log.title}</h2><p className="mt-2 text-xs leading-5 text-slate-600">{log.workContent}</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><p className="rounded bg-emerald-50 p-3 text-xs"><b className="block text-emerald-700">结果</b>{log.result || "未填写"}</p><p className="rounded bg-rose-50 p-3 text-xs"><b className="block text-rose-700">问题</b>{log.problems || "无"}</p><p className="rounded bg-blue-50 p-3 text-xs"><b className="block text-blue-700">下一步</b>{log.nextPlan || "未设置"}</p></div></div><div className="flex shrink-0 flex-wrap gap-1.5 lg:max-w-48"><Button size="sm" variant="ghost" onClick={() => { setEditing(log); setFormOpen(true); }}><Edit3 />编辑</Button><Button size="sm" variant="ghost" onClick={async () => { try { await dispatch({ type: "issue/added", issue: createTechnicalIssue({ projectId: log.projectId, moduleId: log.moduleId, taskId: log.taskId, title: log.problems || `${log.title}中的待解决问题`, phenomenon: log.problems || "从工程日志创建，请补充现象。", errorMessage: "", severity: "S3", status: "待定位", reproductionSteps: "", probableCause: "", rootCause: "", discoveredAt: new Date().toISOString() }) }); setNotice({ id: Date.now(), title: "已创建技术问题", description: "可前往测试与复盘继续处理。" }); } catch (cause: unknown) { setNotice({ id: Date.now(), title: "创建失败", description: cause instanceof Error ? cause.message : "请重试。" }); } }}><Bug />创建问题</Button><Button size="sm" variant="ghost" onClick={async () => { try { await dispatch({ type: "knowledge/added", item: knowledgeFromWorkLog(log) }); setNotice({ id: Date.now(), title: "已沉淀知识", description: "日志已进入知识库收件箱。" }); } catch (cause: unknown) { setNotice({ id: Date.now(), title: "保存失败", description: cause instanceof Error ? cause.message : "请重试。" }); } }}><BookPlus />沉淀知识</Button><Button size="sm" variant="destructive" onClick={() => setDeleting(log)}><Trash2 />删除</Button></div></div></article>; })}</section> : <EmptyState title={data.workLogs.length ? "没有符合条件的日志" : "还没有工程日志"} description="记录一次真实工作过程，后续可继续创建问题和知识。" actionLabel="新增日志" onAction={() => setFormOpen(true)} />}
    <WorkLogDialog open={formOpen} log={editing} data={data} initialProjectId={initialProjectId} initialTaskId={initialTaskId} onClose={() => setFormOpen(false)} onSubmit={save} /><ConfirmDialog open={Boolean(deleting)} title="删除工程日志" description="有关联测试、知识或其他记录时服务器会拒绝删除，请先处理关联。" onCancel={() => setDeleting(null)} onConfirm={() => { if (!deleting) return; void dispatch({ type: "work-log/deleted", workLogId: deleting.id }).then(() => setDeleting(null)).catch((cause: unknown) => setNotice({ id: Date.now(), title: "删除失败", description: cause instanceof Error ? cause.message : "请重试。" })); }} /><ActionToast notice={notice} onDismiss={() => setNotice(null)} /></div>;
}
