"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Edit3, Plus, Trash2 } from "lucide-react";
import { ActionToast, type ToastNotice } from "@/components/layout/action-toast";
import { ProjectStructureDialog } from "@/components/projects/project-structure-dialog";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { EmptyState } from "@/components/shared/empty-state";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { useWorkspaceData } from "@/hooks/use-workspace-data";
import { formatChineseDate } from "@/lib/date";
import { createProjectMilestone, createProjectModule, updateProjectModule } from "@/services/project-service";
import { selectOpenIssues } from "@/services/workspace-selectors";
import type { ProjectMilestone, ProjectMilestoneDraft, ProjectModule, ProjectModuleDraft } from "@/types/project";

export function ProjectDetail({ projectId }: { projectId: string }) {
  const { data, dispatch } = useWorkspaceData(); const project = data.projects.find((item) => item.id === projectId);
  const [dialog, setDialog] = useState<"module" | "milestone" | null>(null); const [module, setModule] = useState<ProjectModule | null>(null); const [milestone, setMilestone] = useState<ProjectMilestone | null>(null); const [deleteModule, setDeleteModule] = useState<ProjectModule | null>(null); const [deletingMilestone, setDeletingMilestone] = useState<ProjectMilestone | null>(null); const [notice, setNotice] = useState<ToastNotice | null>(null);
  if (!project) return <EmptyState title="找不到该项目" description="项目可能已被删除，返回项目中心查看当前数据。" />;
  const modules = data.projectModules.filter((item) => item.projectId === projectId).sort((a, b) => a.sortOrder - b.sortOrder); const milestones = data.projectMilestones.filter((item) => item.projectId === projectId); const tasks = data.tasks.filter((item) => item.projectId === projectId); const logs = data.workLogs.filter((item) => item.projectId === projectId).slice(0, 4); const tests = data.testRecords.filter((item) => item.projectId === projectId).slice(0, 3); const issues = selectOpenIssues(data, projectId); const knowledge = data.knowledgeItems.filter((item) => item.projectId === projectId).slice(0, 4);
  const saveModule = (draft: ProjectModuleDraft, current?: ProjectModule | null) => dispatch(current ? { type: "project-module/updated", module: updateProjectModule({ ...current, ...draft }) } : { type: "project-module/added", module: createProjectModule(draft) });
  const saveMilestone = (draft: ProjectMilestoneDraft, current?: ProjectMilestone | null) => dispatch(current ? { type: "milestone/updated", milestone: { ...current, ...draft } } : { type: "milestone/added", milestone: createProjectMilestone(draft) });
  return <div className="space-y-5"><Link href="/projects" className="inline-flex items-center gap-2 text-xs text-slate-500 hover:text-blue-700"><ArrowLeft className="h-4 w-4" />返回项目中心</Link><header className="rounded-lg border border-border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div><div className="flex gap-2 text-[10px]"><span className="rounded bg-blue-50 px-2 py-1 text-blue-700">{project.category}</span><span className="rounded bg-slate-100 px-2 py-1 text-slate-600">{project.status}</span><span className="px-2 py-1 text-slate-400">{project.code}</span></div><h1 className="mt-3 text-2xl font-semibold">{project.name}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{project.description}</p><p className="mt-3 text-xs text-slate-500">{project.role} · {formatChineseDate(project.startDate)} 至 {formatChineseDate(project.endDate)}</p></div><div className="w-full lg:w-52"><p className="text-right text-3xl font-semibold text-blue-700">{project.progress}%</p><Progress value={project.progress} className="mt-3 h-2" /></div></div></header>
    <section className="grid gap-4 xl:grid-cols-2"><div className="rounded-lg border border-border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">项目模块</h2><Button size="sm" onClick={() => { setModule(null); setDialog("module"); }}><Plus />新增模块</Button></div><div className="divide-y">{modules.map((item) => <article key={item.id} className="p-4"><div className="flex justify-between gap-3"><button type="button" className="text-left" onClick={() => { setModule(item); setDialog("module"); }}><p className="text-sm font-medium">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.currentTarget}</p></button><div className="flex items-center gap-2"><span className="text-sm text-blue-700">{item.progress}%</span><button aria-label={`删除模块 ${item.name}`} onClick={() => setDeleteModule(item)} className="text-rose-600"><Trash2 className="h-4 w-4" /></button></div></div><Progress value={item.progress} className="mt-3 h-1.5" /></article>)}</div></div>
      <div className="rounded-lg border border-border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">里程碑</h2><Button size="sm" onClick={() => { setMilestone(null); setDialog("milestone"); }}><Plus />新增里程碑</Button></div>{milestones.length ? <div className="divide-y">{milestones.map((item) => <article key={item.id} className="flex flex-col justify-between gap-3 p-4 hover:bg-slate-50 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{item.title}</p><span className="text-xs text-slate-500">{formatChineseDate(item.targetDate)}</span></div><p className="mt-1 text-xs text-slate-500">{item.status} · {item.progress}%</p></div><div className="flex shrink-0 gap-2"><Button size="sm" variant="ghost" onClick={() => { setMilestone(item); setDialog("milestone"); }}><Edit3 />编辑</Button><Button size="sm" variant="destructive" aria-label={`删除里程碑 ${item.title}`} onClick={() => setDeletingMilestone(item)}><Trash2 />删除</Button></div></article>)}</div> : <EmptyState title="还没有里程碑" description="新增里程碑后，它会自动出现在日历计划中。" actionLabel="新增里程碑" onAction={() => { setMilestone(null); setDialog("milestone"); }} />}</div></section>
    <section className="grid gap-4 lg:grid-cols-3"><Summary title="关联任务" items={tasks.map((item) => item.title)} href="/today" /><Summary title="最近工程日志" items={logs.map((item) => item.title)} href={`/logs?projectId=${projectId}`} /><Summary title="未解决问题" items={issues.map((item) => item.title)} href={`/reviews?projectId=${projectId}`} /><Summary title="最近测试" items={tests.map((item) => item.title)} href={`/reviews?projectId=${projectId}`} /><Summary title="知识成果" items={knowledge.map((item) => item.title)} href={`/knowledge?projectId=${projectId}`} /><Summary title="报告与简历" items={[`${data.reports.filter((item) => item.projectId === projectId).length} 份报告`, `${data.resumeMaterials.filter((item) => item.projectId === projectId).length} 条简历素材`]} href={`/reports?projectId=${projectId}`} /></section>
    <ProjectStructureDialog open={Boolean(dialog)} kind={dialog ?? "module"} projectId={projectId} module={module} milestone={milestone} onClose={() => setDialog(null)} onModule={saveModule} onMilestone={saveMilestone} />
    <ConfirmDialog open={Boolean(deleteModule)} title="删除项目模块" description="模块会被删除，关联任务、日志、测试、问题和知识仅清空 moduleId，不会丢失。" onCancel={() => setDeleteModule(null)} onConfirm={() => { if (deleteModule) dispatch({ type: "project-module/deleted", moduleId: deleteModule.id }); setDeleteModule(null); setNotice({ id: Date.now(), title: "模块已删除", description: "关联实体已保留并解除模块关联。" }); }} />
    <ConfirmDialog open={Boolean(deletingMilestone)} title="删除里程碑" description={`确定删除里程碑“${deletingMilestone?.title ?? "该里程碑"}”（目标日期：${deletingMilestone ? formatChineseDate(deletingMilestone.targetDate) : "未知"}）吗？删除后对应的日历派生日程也会消失；该操作不会删除项目、任务或日志。`} onCancel={() => setDeletingMilestone(null)} onConfirm={() => { if (!deletingMilestone) return; dispatch({ type: "milestone/deleted", milestoneId: deletingMilestone.id }); if (milestone?.id === deletingMilestone.id) { setDialog(null); setMilestone(null); } setDeletingMilestone(null); setNotice({ id: Date.now(), title: "里程碑已删除", description: "对应的日历派生日程已同步移除" }); }} />
    <ActionToast notice={notice} onDismiss={() => setNotice(null)} /></div>;
}
function Summary({ title, items, href }: { title: string; items: string[]; href: string }) { return <article className="rounded-lg border border-border bg-white p-4 shadow-sm"><div className="flex justify-between"><h2 className="text-sm font-semibold">{title}</h2><Link href={href} className="text-[11px] text-blue-600">查看</Link></div><div className="mt-3 space-y-2">{items.length ? items.slice(0, 4).map((item) => <p key={item} className="truncate text-xs text-slate-500">{item}</p>) : <p className="text-xs text-slate-400">暂无数据</p>}</div></article>; }
