"use client";
import { useEffect, useState } from "react";
import { Dialog } from "@/components/shared/dialog";
import { FormField } from "@/components/shared/form-field";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { localDateKeyWithOffset } from "@/lib/date";
import type { ProjectMilestone, ProjectMilestoneDraft, ProjectModule, ProjectModuleDraft } from "@/types/project";

interface Props { open: boolean; kind: "module" | "milestone"; projectId: string; module?: ProjectModule | null; milestone?: ProjectMilestone | null; onClose: () => void; onModule: (draft: ProjectModuleDraft, current?: ProjectModule | null) => Promise<unknown> | void; onMilestone: (draft: ProjectMilestoneDraft, current?: ProjectMilestone | null) => Promise<unknown> | void; }
export function ProjectStructureDialog({ open, kind, projectId, module, milestone, onClose, onModule, onMilestone }: Props) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [target, setTarget] = useState(""); const [progress, setProgress] = useState("0"); const [status, setStatus] = useState(""); const [date, setDate] = useState(localDateKeyWithOffset(new Date(), 14)); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; setName(kind === "module" ? module?.name ?? "" : milestone?.title ?? ""); setDescription(kind === "module" ? module?.description ?? "" : milestone?.description ?? ""); setProgress(String(kind === "module" ? module?.progress ?? 0 : milestone?.progress ?? 0)); setStatus(kind === "module" ? module?.status ?? "开发中" : milestone?.status ?? "未开始"); setTarget(module?.currentTarget ?? ""); setDate(milestone?.targetDate ?? localDateKeyWithOffset(new Date(), 14)); setError(""); }, [kind, milestone, module, open]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) { setError("名称不能为空。"); return; } try { if (kind === "module") await onModule({ projectId, name: name.trim(), description, owner: "CDC", status: status as ProjectModule["status"], priority: module?.priority ?? "中", progress: Number(progress), currentTarget: target, sortOrder: module?.sortOrder ?? 99, parentId: module?.parentId }, module); else await onMilestone({ projectId, title: name.trim(), description, targetDate: date, completedDate: milestone?.completedDate, status: status as ProjectMilestone["status"], progress: Number(progress) }, milestone); onClose(); } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : "服务器保存失败。"); } };
  return <Dialog open={open} title={`${module || milestone ? "编辑" : "新增"}${kind === "module" ? "项目模块" : "里程碑"}`} onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>取消</Button><Button type="submit" form="structure-form">保存</Button></>}><form id="structure-form" onSubmit={submit} className="space-y-4"><FormField label={kind === "module" ? "模块名称" : "里程碑标题"} htmlFor="structure-name" error={error}><Input id="structure-name" value={name} onChange={(e) => setName(e.target.value)} /></FormField><FormField label="描述" htmlFor="structure-description"><Textarea id="structure-description" value={description} onChange={(e) => setDescription(e.target.value)} /></FormField><div className="grid gap-4 sm:grid-cols-2"><FormField label="状态" htmlFor="structure-status"><Select id="structure-status" value={status} onChange={(e) => setStatus(e.target.value)}>{(kind === "module" ? ["规划中", "开发中", "验证中", "稳定", "已暂停"] : ["未开始", "进行中", "已完成", "延期"]).map((item) => <option key={item}>{item}</option>)}</Select></FormField><FormField label="进度" htmlFor="structure-progress"><Input id="structure-progress" type="number" min="0" max="100" value={progress} onChange={(e) => setProgress(e.target.value)} /></FormField></div>{kind === "module" ? <FormField label="当前目标" htmlFor="structure-target"><Input id="structure-target" value={target} onChange={(e) => setTarget(e.target.value)} /></FormField> : <FormField label="目标日期" htmlFor="structure-date"><Input id="structure-date" type="date" value={date} onChange={(e) => setDate(e.target.value)} /></FormField>}</form></Dialog>;
}
